language: rust

dist: bionic
rust:
  - stable
  - beta
  - nightly

cache: cargo

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"

addons:
  apt:
    packages:
      - build-essential
      - yasm

script:
  - travis_wait cargo test --verbose --features build
