language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"

addons:
  apt:
    packages:
      - yasm
      - autoconf
      - automake
      - build-essential
      - cmake
      - git-core
      - libass-dev
      - libfreetype6-dev
      - libsdl2-dev
      - libtool
      - libva-dev
      - libvdpau-dev
      - libvorbis-dev
      - libxcb1-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - pkg-config
      - texinfo
      - wget
      - zlib1g-dev

script:
  - travis_wait cargo test --verbose --features build
